services:
  # Servicio 1: Base de Datos de Grafos (No cambia, Neo4j corre bien en CPU)
  neo4j_db:
    image: neo4j:5.16.0
    container_name: precog_neo4j_demo
    ports:
      - "7474:7474" # HTTP (Browser)
      - "7687:7687" # Bolt (Protocolo binario)
    environment:
      - NEO4J_AUTH=neo4j/secret_password_123
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./neo4j_data_demo:/data # Persistencia separada para demo

  # Servicio 2: Tu API de Pre-Crimen (Modo CPU Lightweight)
  precog_api:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: precog_brain_demo
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secret_password_123
      - DEMO_MODE=True
    depends_on:
      - neo4j_db
    volumes:
      - ./app:/code/app # Hot-reload
      - ./data:/code/data # Map data folder for parquet files
