"""
Neo4j Data Fetcher for GAT Model Training

This utility fetches pre-processed graph data from Neo4j database
(as generated by the dataEngineer branch scripts) and converts it
to PyTorch Geometric format suitable for GAT model training.

Based on the data structure from dataEngineer branch:
- src/ai/graph_loader.py
- src/scripts/init_city_graph.py
"""

import torch
import pandas as pd
import numpy as np
import logging
import os
from datetime import datetime
from typing import Tuple, Optional
from torch_geometric.data import Data

try:
    from neo4j import Driver, GraphDatabase
    NEO4J_AVAILABLE = True
except ImportError:
    NEO4J_AVAILABLE = False
    logging.warning("Neo4j driver not available. Install with: pip install neo4j")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class Neo4jDataFetcher:
    """
    Fetches graph data from Neo4j database for GAT model training.
    
    Expected Neo4j schema (from dataEngineer branch):
    - Nodes: Citizen(id, name, born, risk_seed, job, criminal_degree)
    - Nodes: Location(id, name, type, env_risk, coord)
    - Relationships: (:Citizen)-[:KNOWS]->(:Citizen)
    - Relationships: (:Citizen)-[:COMMITTED_CRIME]->(...)
    - Relationships: (:Citizen)-[:VISITED]->(:Location)
    """
    
    def __init__(self, uri: str = "EntrenoParaCere", 
                 user: str = "neo4j", 
                 password: str = "A8ZCorbDG8GNBbM2y5PhK3QOwNSdy1SykRkn-BcEVfg"):
        """
        Initialize Neo4j connection.
        
        Args:
            uri: Neo4j connection URI (default: from NEO4J_URI env or bolt://localhost:7687)
            user: Database username (default: from NEO4J_USER env or neo4j)
            password: Database password (default: from NEO4J_PASSWORD env or prompts if not set)
        """
        if not NEO4J_AVAILABLE:
            raise ImportError("Neo4j driver not installed. Install with: pip install neo4j")
        
        # Get credentials from environment or use defaults
        self.uri = uri or os.getenv("NEO4J_URI", "bolt://localhost:7687")
        user = user or os.getenv("NEO4J_USER", "neo4j")
        password = password or os.getenv("NEO4J_PASSWORD", "minorityreport")
        
        self.driver = GraphDatabase.driver(self.uri, auth=(user, password))
        logger.info(f"Connected to Neo4j at {self.uri}")
    
    def close(self):
        """Close Neo4j connection."""
        if self.driver:
            self.driver.close()
            logger.info("Neo4j connection closed")
    
    def verify_connection(self) -> bool:
        """
        Verify that Neo4j is accessible and contains data.
        
        Returns:
            True if connection is valid and data exists
        """
        try:
            with self.driver.session() as session:
                result = session.run("MATCH (c:Citizen) RETURN count(c) as count")
                count = result.single()["count"]
                logger.info(f"✅ Neo4j connected. Found {count} citizens.")
                return count > 0
        except Exception as e:
            logger.error(f"❌ Neo4j connection failed: {e}")
            return False
    
    def calculate_criminal_influence(self):
        """
        Calculate criminal influence metric for each citizen.
        Updates Citizen nodes with 'criminal_degree' property.
        
        This replicates the metric calculation from dataEngineer/graph_loader.py
        """
        logger.info("📊 Calculating criminal influence...")
        query = """
        MATCH (c:Citizen)
        OPTIONAL MATCH (c)-[:KNOWS]-(friend)-[:COMMITTED_CRIME]->()
        WITH c, count(distinct friend) as criminal_friends
        SET c.criminal_degree = criminal_friends
        RETURN count(c) as count
        """
        try:
            with self.driver.session() as session:
                result = session.run(query)
                count = result.single()["count"]
                logger.info(f"✅ Updated {count} citizens with criminal_degree")
        except Exception as e:
            logger.error(f"Failed to calculate criminal influence: {e}")
            raise
    
    def extract_features_to_pandas(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Extract citizen features from Neo4j and process them.
        
        Returns:
            Tuple of (raw_df, features_df)
            - raw_df: Contains id, born, job, criminal_degree, risk_seed
            - features_df: Processed features ready for ML (age, job_*, crim_deg)
        """
        logger.info("📊 Extracting citizen features from Neo4j...")
        
        query = """
        MATCH (c:Citizen)
        RETURN c.id as id, c.born as born, c.job as job, 
               c.criminal_degree as crim_deg, c.risk_seed as target
        ORDER BY c.id ASC
        """
        
        with self.driver.session() as session:
            result = session.run(query)
            data = [r.data() for r in result]
        
        if not data:
            logger.warning("⚠️  No citizen data found in Neo4j!")
            return pd.DataFrame(), pd.DataFrame()
        
        df = pd.DataFrame(data)
        
        # Age normalization (same as dataEngineer/graph_loader.py)
        current_year = datetime.now().year
        df['born'] = pd.to_numeric(df['born'], errors='coerce').fillna(current_year)
        df['age'] = (current_year - df['born']) / 100.0
        
        # One-hot encode jobs
        job_dummies = pd.get_dummies(df['job'], prefix='job')
        job_dummies = job_dummies.astype(int)
        
        df_processed = pd.concat([df, job_dummies], axis=1)
        
        # Keep only ML features
        drop_cols = ['born', 'job', 'target', 'id']
        features = df_processed.drop(columns=drop_cols)
        
        logger.info(f"✅ Extracted {len(df)} citizens with {features.shape[1]} features")
        return df, features
    
    def extract_graph_edges(self) -> pd.DataFrame:
        """
        Extract social network edges (KNOWS relationships).
        
        Returns:
            DataFrame with columns: source, target
        """
        logger.info("🔗 Extracting graph edges...")
        
        query = """
        MATCH (c1:Citizen)-[:KNOWS]->(c2:Citizen)
        RETURN c1.id as source, c2.id as target
        """
        
        with self.driver.session() as session:
            result = session.run(query)
            edges = [r.data() for r in result]
        
        if not edges:
            logger.warning("⚠️  No edges found!")
            return pd.DataFrame(columns=['source', 'target'])
        
        edges_df = pd.DataFrame(edges)
        logger.info(f"✅ Extracted {len(edges_df)} edges")
        return edges_df
    
    def build_pyg_data(self, features_df: pd.DataFrame, 
                       raw_df: pd.DataFrame, 
                       edges_df: pd.DataFrame) -> Data:
        """
        Build PyTorch Geometric Data object.
        
        Args:
            features_df: Processed features (age, job_*, crim_deg)
            raw_df: Raw data with target labels
            edges_df: Graph edges (source, target)
        
        Returns:
            PyTorch Geometric Data object
        """
        logger.info("🚀 Building PyTorch Geometric Data object...")
        
        if features_df.empty:
            raise ValueError("Features DataFrame is empty!")
        
        # 1. Node features (X)
        x = torch.tensor(features_df.values, dtype=torch.float)
        
        # 2. Labels (Y) - risk_seed
        y = torch.tensor(raw_df['target'].values, dtype=torch.float).view(-1, 1)
        
        # 3. Edge index
        if edges_df.empty:
            logger.warning("⚠️  No edges! Creating empty edge_index")
            edge_index = torch.empty((2, 0), dtype=torch.long)
        else:
            # Create node ID to index mapping
            node_ids = sorted(raw_df['id'].unique())
            id_to_idx = {node_id: idx for idx, node_id in enumerate(node_ids)}
            
            # Map edge IDs to indices
            source_indices = edges_df['source'].map(id_to_idx)
            target_indices = edges_df['target'].map(id_to_idx)
            
            # Create bidirectional edges
            edge_index = torch.tensor([
                list(source_indices) + list(target_indices),
                list(target_indices) + list(source_indices)
            ], dtype=torch.long)
        
        data = Data(x=x, edge_index=edge_index, y=y)
        
        logger.info(f"✅ Created PyG Data: {data.num_nodes} nodes, "
                   f"{data.num_edges} edges, {data.num_features} features")
        
        return data
    
    def fetch_graph_data(self, calculate_metrics: bool = True) -> Data:
        """
        Main method to fetch complete graph data from Neo4j.
        
        Args:
            calculate_metrics: Whether to calculate criminal_degree before fetching
        
        Returns:
            PyTorch Geometric Data object ready for GAT training
        """
        logger.info("🎯 Fetching complete graph data from Neo4j...")
        
        # Verify connection
        if not self.verify_connection():
            raise ConnectionError("Cannot connect to Neo4j or no data available")
        
        # Calculate metrics if requested
        if calculate_metrics:
            self.calculate_criminal_influence()
        
        # Extract data
        raw_df, features_df = self.extract_features_to_pandas()
        edges_df = self.extract_graph_edges()
        
        # Build PyG Data
        data = self.build_pyg_data(features_df, raw_df, edges_df)
        
        logger.info("✅ Graph data fetched successfully!")
        return data
    
    def get_pyg_data(self, relationship_type: str = "KNOWS") -> Optional[Data]:
        """
        Get PyG Data object using specified relationship type.
        Compatible with dataEngineer branch schema.
        
        Args:
            relationship_type: Edge type to use (KNOWS, INTERACTS_WITH, etc.)
        
        Returns:
            PyTorch Geometric Data object
        """
        logger.info(f"📊 Fetching citizen graph with {relationship_type} edges...")
        
        # Fetch nodes with extended properties - use exact property names from seed_neo4j.py
        node_query = """
        MATCH (c:Citizen)
        RETURN c.id as id, 
               c.born as born, 
               c.job as job,
               coalesce(c.criminalDegree, 0) as crim_deg,
               coalesce(c.preCrimeRiskScore, 0.5) as target,
               coalesce(c.preCrimeRiskScore, 0.5) as risk_score,
               coalesce(c.criminalRecord, 0) as criminal_record
        ORDER BY c.id ASC
        """
        
        # Fetch edges
        edge_query = f"""
        MATCH (c1:Citizen)-[r:{relationship_type}]->(c2:Citizen)
        RETURN c1.id as source, c2.id as target
        """
        
        try:
            with self.driver.session() as session:
                # Get nodes
                node_result = session.run(node_query)
                nodes = [dict(r) for r in node_result]
                
                if not nodes:
                    logger.warning("No citizens found!")
                    return None
                
                # Get edges
                edge_result = session.run(edge_query)
                edges = [dict(r) for r in edge_result]
            
            # Process node features
            df = pd.DataFrame(nodes)
            
            # Handle missing values
            df['born'] = pd.to_numeric(df['born'], errors='coerce')
            df['crim_deg'] = pd.to_numeric(df['crim_deg'], errors='coerce').fillna(0)
            df['target'] = pd.to_numeric(df['target'], errors='coerce').fillna(0.5)
            df['risk_score'] = pd.to_numeric(df['risk_score'], errors='coerce').fillna(0.5)
            df['criminal_record'] = pd.to_numeric(df['criminal_record'], errors='coerce').fillna(0)
            
            current_year = datetime.now().year
            df['born'] = df['born'].fillna(current_year - 30)
            df['age'] = (current_year - df['born']) / 100.0
            
            # One-hot encode jobs
            df['job'] = df['job'].fillna('unknown')
            job_dummies = pd.get_dummies(df['job'], prefix='job')
            
            # Build feature matrix with numeric features only
            feature_cols = ['age', 'crim_deg', 'risk_score', 'criminal_record']
            for col in job_dummies.columns:
                df[col] = job_dummies[col].astype(float)
                feature_cols.append(col)
            
            # Make sure all features are numeric
            x_values = df[feature_cols].values.astype(np.float32)
            x = torch.tensor(x_values, dtype=torch.float)
            
            # Labels (binary classification based on risk)
            risk_threshold = df['target'].median()
            y = torch.tensor((df['target'] > risk_threshold).astype(np.int64).values, dtype=torch.long)
            
            # Build edge index
            if edges and len(edges) > 0:
                node_ids = sorted(df['id'].unique())
                id_to_idx = {int(nid): idx for idx, nid in enumerate(node_ids)}
                
                edge_src = []
                edge_tgt = []
                
                for e in edges:
                    src_id = int(e['source']) if e['source'] is not None else None
                    tgt_id = int(e['target']) if e['target'] is not None else None
                    
                    if src_id in id_to_idx and tgt_id in id_to_idx:
                        edge_src.append(id_to_idx[src_id])
                        edge_tgt.append(id_to_idx[tgt_id])
                
                edge_index = torch.tensor([edge_src, edge_tgt], dtype=torch.long)
            else:
                edge_index = torch.empty((2, 0), dtype=torch.long)
            
            data = Data(x=x, edge_index=edge_index, y=y)
            logger.info(f"✅ Citizen graph: {data.num_nodes} nodes, {data.num_edges} edges, {data.num_features} features")
            return data
            
        except Exception as e:
            logger.error(f"Failed to fetch citizen graph: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    def fetch_location_graph(self) -> Optional[Data]:
        """
        Fetch Location graph for escape route optimization.
        Compatible with dataEngineer branch schema.
        
        Returns:
            PyTorch Geometric Data object for locations
        """
        logger.info("🗺️ Fetching location graph...")
        
        # Fetch location nodes
        node_query = """
        MATCH (l:Location)
        RETURN l.id as id,
               l.name as name,
               coalesce(l.policeLevel, 0.5) as police_level,
               coalesce(l.locationType, 0) as loc_type,
               coalesce(l.illumination, 0.5) as illumination,
               coalesce(l.density, 0.5) as density,
               coalesce(l.envRisk, l.env_risk, 0.5) as env_risk,
               coalesce(l.latitude, 0) as lat,
               coalesce(l.longitude, 0) as lng
        ORDER BY l.id ASC
        """
        
        # Fetch connections
        edge_query = """
        MATCH (l1:Location)-[r:CONNECTED_TO]->(l2:Location)
        RETURN l1.id as source, 
               l2.id as target,
               coalesce(r.distance, 1.0) as distance,
               coalesce(r.surveillanceLevel, 0.5) as surveillance
        """
        
        try:
            with self.driver.session() as session:
                # Get nodes
                node_result = session.run(node_query)
                nodes = [r.data() for r in node_result]
                
                if not nodes:
                    logger.warning("No locations found!")
                    return None
                
                # Get edges
                edge_result = session.run(edge_query)
                edges = [r.data() for r in edge_result]
            
            # Build feature matrix
            df = pd.DataFrame(nodes)
            feature_cols = ['police_level', 'loc_type', 'illumination', 'density', 'env_risk', 'lat', 'lng']
            
            # Normalize coordinates
            if df['lat'].std() > 0:
                df['lat'] = (df['lat'] - df['lat'].mean()) / df['lat'].std()
                df['lng'] = (df['lng'] - df['lng'].mean()) / df['lng'].std()
            
            x = torch.tensor(df[feature_cols].values, dtype=torch.float)
            
            # Store police level for labeling
            police_level = torch.tensor(df['police_level'].values, dtype=torch.float)
            
            # Build edge index
            if edges:
                node_ids = sorted(df['id'].unique())
                id_to_idx = {nid: idx for idx, nid in enumerate(node_ids)}
                
                edge_src = []
                edge_tgt = []
                edge_attr = []
                
                for e in edges:
                    if e['source'] in id_to_idx and e['target'] in id_to_idx:
                        edge_src.append(id_to_idx[e['source']])
                        edge_tgt.append(id_to_idx[e['target']])
                        edge_attr.append([e['distance'], e['surveillance']])
                
                edge_index = torch.tensor([edge_src, edge_tgt], dtype=torch.long)
                edge_attr_tensor = torch.tensor(edge_attr, dtype=torch.float) if edge_attr else None
            else:
                edge_index = torch.empty((2, 0), dtype=torch.long)
                edge_attr_tensor = None
            
            data = Data(x=x, edge_index=edge_index)
            data.police_level = police_level
            data.location_names = df['name'].tolist()
            
            if edge_attr_tensor is not None:
                data.edge_attr = edge_attr_tensor
            
            logger.info(f"✅ Location graph: {data.num_nodes} nodes, {data.num_edges} edges")
            return data
            
        except Exception as e:
            logger.error(f"Failed to fetch location graph: {e}")
            return None


def fetch_graph_data(uri: str = None,
                     user: str = None,
                     password: str = None) -> Optional[Data]:
    """
    Convenience function to fetch graph data from Neo4j.
    
    Usage:
        data = fetch_graph_data()
        if data:
            print(f"Loaded {data.num_nodes} nodes with {data.num_features} features")
    
    Args:
        uri: Neo4j connection URI
        user: Database username
        password: Database password
    
    Returns:
        PyTorch Geometric Data object or None if failed
    """
    fetcher = None
    try:
        fetcher = Neo4jDataFetcher(uri, user, password)
        data = fetcher.fetch_graph_data()
        return data
    except Exception as e:
        logger.error(f"Failed to fetch graph data: {e}")
        return None
    finally:
        if fetcher:
            fetcher.close()


if __name__ == "__main__":
    # Test the data fetcher
    print("=" * 60)
    print("Testing Neo4j Data Fetcher")
    print("=" * 60)
    
    data = fetch_graph_data()
    
    if data:
        print("\n✅ Successfully loaded graph data!")
        print(f"   Nodes: {data.num_nodes}")
        print(f"   Edges: {data.num_edges}")
        print(f"   Features: {data.num_features}")
        print(f"   Labels shape: {data.y.shape}")
        print(f"\n   Sample features (first 3 nodes):")
        print(data.x[:3])
        print(f"\n   Sample labels (first 5 nodes):")
        print(data.y[:5].squeeze())
    else:
        print("\n❌ Failed to load graph data")
        print("   Make sure Neo4j is running and contains data")
        print("   Run the init_city_graph.py script from dataEngineer branch first")
