"""
Export Data from Neo4j to Files

This script exports the graph data from Neo4j (generated by dataEngineer branch)
to CSV and PyTorch tensor files for offline training.

Usage:
    python scripts/export_data_from_neo4j.py --output data/
    python scripts/export_data_from_neo4j.py --output data/ --format pytorch
"""

import argparse
import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import torch
import pandas as pd
import logging

from src.utils.neo4j_data_fetcher import Neo4jDataFetcher

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def export_to_csv(output_dir: str, 
                  raw_df: pd.DataFrame, 
                  features_df: pd.DataFrame, 
                  edges_df: pd.DataFrame):
    """
    Export data to CSV files.
    
    Args:
        output_dir: Directory to save CSV files
        raw_df: Raw citizen data with targets
        features_df: Processed features
        edges_df: Graph edges
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Save citizens with all info
    citizens_file = os.path.join(output_dir, "citizens.csv")
    raw_df.to_csv(citizens_file, index=False)
    logger.info(f"✅ Saved citizens data: {citizens_file}")
    
    # Save processed features
    features_file = os.path.join(output_dir, "features.csv")
    features_df.to_csv(features_file, index=False)
    logger.info(f"✅ Saved features: {features_file}")
    
    # Save edges
    edges_file = os.path.join(output_dir, "edges.csv")
    edges_df.to_csv(edges_file, index=False)
    logger.info(f"✅ Saved edges: {edges_file}")
    
    # Save feature names for reference
    feature_names_file = os.path.join(output_dir, "feature_names.txt")
    with open(feature_names_file, 'w') as f:
        f.write('\n'.join(features_df.columns))
    logger.info(f"✅ Saved feature names: {feature_names_file}")


def export_to_pytorch(output_dir: str, data):
    """
    Export PyTorch Geometric Data to .pt files.
    
    Args:
        output_dir: Directory to save PyTorch files
        data: PyTorch Geometric Data object
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Save complete data object
    data_file = os.path.join(output_dir, "graph_data.pt")
    torch.save(data, data_file)
    logger.info(f"✅ Saved PyTorch Geometric Data: {data_file}")
    
    # Save individual components for flexibility
    x_file = os.path.join(output_dir, "node_features.pt")
    torch.save(data.x, x_file)
    logger.info(f"✅ Saved node features: {x_file}")
    
    edge_index_file = os.path.join(output_dir, "edge_index.pt")
    torch.save(data.edge_index, edge_index_file)
    logger.info(f"✅ Saved edge index: {edge_index_file}")
    
    y_file = os.path.join(output_dir, "labels.pt")
    torch.save(data.y, y_file)
    logger.info(f"✅ Saved labels: {y_file}")


def export_metadata(output_dir: str, data):
    """
    Export metadata about the dataset.
    
    Args:
        output_dir: Directory to save metadata
        data: PyTorch Geometric Data object
    """
    metadata_file = os.path.join(output_dir, "metadata.txt")
    
    with open(metadata_file, 'w') as f:
        f.write("# Graph Dataset Metadata\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Number of nodes: {data.num_nodes}\n")
        f.write(f"Number of edges: {data.num_edges}\n")
        f.write(f"Number of features: {data.num_features}\n")
        f.write(f"Label shape: {data.y.shape}\n")
        f.write(f"\nFeature tensor shape: {data.x.shape}\n")
        f.write(f"Edge index shape: {data.edge_index.shape}\n")
        f.write(f"\nFeature statistics:\n")
        f.write(f"  Mean: {data.x.mean(dim=0).tolist()}\n")
        f.write(f"  Std:  {data.x.std(dim=0).tolist()}\n")
        f.write(f"\nLabel statistics:\n")
        f.write(f"  Min:  {data.y.min().item():.4f}\n")
        f.write(f"  Max:  {data.y.max().item():.4f}\n")
        f.write(f"  Mean: {data.y.mean().item():.4f}\n")
        f.write(f"  Std:  {data.y.std().item():.4f}\n")
        f.write(f"\nGraph density: {data.num_edges / (data.num_nodes * (data.num_nodes - 1)):.6f}\n")
        f.write(f"Average degree: {data.num_edges / data.num_nodes:.2f}\n")
    
    logger.info(f"✅ Saved metadata: {metadata_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Export graph data from Neo4j to files"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="data",
        help="Output directory for exported files (default: data/)"
    )
    parser.add_argument(
        "--format", "-f",
        type=str,
        choices=["csv", "pytorch", "both"],
        default="both",
        help="Export format: csv, pytorch, or both (default: both)"
    )
    parser.add_argument(
        "--uri",
        type=str,
        default=None,
        help="Neo4j URI (default: from NEO4J_URI env or bolt://localhost:7687)"
    )
    parser.add_argument(
        "--user",
        type=str,
        default=None,
        help="Neo4j username (default: from NEO4J_USER env or neo4j)"
    )
    parser.add_argument(
        "--password",
        type=str,
        default=None,
        help="Neo4j password (default: from NEO4J_PASSWORD env or default)"
    )
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("Exporting Graph Data from Neo4j")
    print("=" * 60)
    print(f"Output directory: {args.output}")
    print(f"Export format: {args.format}")
    print("=" * 60 + "\n")
    
    # Create data fetcher
    fetcher = None
    try:
        fetcher = Neo4jDataFetcher(args.uri, args.user, args.password)
        
        # Verify connection
        if not fetcher.verify_connection():
            logger.error("❌ Cannot connect to Neo4j or no data available")
            logger.error("   Make sure Neo4j is running and contains data")
            logger.error("   Run init_city_graph.py from dataEngineer branch first")
            return
        
        # Calculate metrics
        fetcher.calculate_criminal_influence()
        
        # Extract data
        raw_df, features_df = fetcher.extract_features_to_pandas()
        edges_df = fetcher.extract_graph_edges()
        
        # Build PyG data
        data = fetcher.build_pyg_data(features_df, raw_df, edges_df)
        
        # Export based on format
        if args.format in ["csv", "both"]:
            logger.info("\n📦 Exporting to CSV format...")
            export_to_csv(args.output, raw_df, features_df, edges_df)
        
        if args.format in ["pytorch", "both"]:
            logger.info("\n📦 Exporting to PyTorch format...")
            export_to_pytorch(args.output, data)
        
        # Always export metadata
        logger.info("\n📝 Exporting metadata...")
        export_metadata(args.output, data)
        
        print("\n" + "=" * 60)
        print("✅ Export completed successfully!")
        print("=" * 60)
        print(f"\nExported files in: {args.output}/")
        print("\nDataset summary:")
        print(f"  Nodes:    {data.num_nodes}")
        print(f"  Edges:    {data.num_edges}")
        print(f"  Features: {data.num_features}")
        print(f"\nYou can now train GAT models using this exported data!")
        
    except Exception as e:
        logger.error(f"\n❌ Export failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        if fetcher:
            fetcher.close()


if __name__ == "__main__":
    main()
